config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:registrations, :sessions]
  root 'groups#index'
  resources :groups, except: [:destroy, :show]
  scope module: :groups do
    resources :groups, only: :none do
      resources :messages, only: [:index, :create]
    end
  end
  resources :users, only: :none do
    collection { get :search }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_group.rb
class ChatGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true

  has_many :users, through: :chat_groups
  has_many :chat_groups
  has_many :messages

  accepts_nested_attributes_for :chat_groups

  scope :order_by_desc, -> { order(created_at: :desc) }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :text, :group_id, :user_id, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :groups, through: :chat_groups
  has_many :chat_groups
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/groups/messages_controller.rb
class Groups::MessagesController < ApplicationController
  include Groups::MessageHelper
  before_action :set_group, only: %i(index create)

  def index
    @groups   = current_user.groups.order_by_desc
    @message  = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { render json: @messages.to_json(include: :user) }
    end
  end

  def create
    @message = current_user.messages.build(create_params)
    @message.save
    respond_to do |format|
      format.json
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def create_params
    params.require(:message).permit(:text, :image).merge(group_id: params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i(edit update)

  def index
    @groups = current_user.groups.order_by_desc
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'Group was successfully created.'
    else
      flash[:alert] = 'Group failed to be created.'
      render :new
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: 'Group was successfully edited.'
    else
      flash[:alert] = 'Group failed to be edited.'
      render :edit
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    users = User.where('name LIKE ?', "%#{params[:input]}%")
                .reject { |user| user.id == current_user.id }
    respond_to do |format|
      format.json { render json: users }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups/message_helper.rb
module Groups::MessageHelper
  def group_users(group)
    group.users.pluck(:name).join(' ')
  end

  def format_date(message)
    message.created_at.strftime('%Y/%m/%d %H:%M:%S')
  end
end

app/views/groups/_form.html.haml
= form_for group, id: 'new_chat_group', class: 'new_chat_group' do |f|
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, :グループ名, class: 'chat-group-form__label', for: 'group[name]'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat-group-form__input', placeholder: 'グループ名を入力してください'

  .chat-group-form__field#display_list
    .chat-group-form__field--left
      %label.chat-group-form__label チャットメンバーを追加
    .chat-group-form__field--right#member
      .chat-group-form__search
        %input.chat-group-form__input#user-search-field{ placeholder: '追加したいユーザー名を入力してください' }

  .chat-group-form__field#user_list
    .chat-group-form__field--left
      %label.chat-group-form__label チャットメンバー
    - if action_name == 'new'
      .chat-group-form__field--right
        .chat-group-user
          %p.chat-group-user__name
            = current_user.name
            = hidden_field_tag 'group[user_ids][]', current_user.id
    - group.users.each do |user|
      .chat-group-form__field--right
        .chat-group-user
          %p.chat-group-user__name
            = user.name
            = hidden_field_tag 'group[user_ids][]', user.id
          - unless current_user.id == user.id
            %p.chat-group-button.delete 削除

  .chat-group-form__field
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit 'Save', class: 'chat-group-form__action-btn', data: { disable_with: '保存中...' }

app/views/groups/_group.slim
= link_to group_messages_path(group) do
  .side__group__list
    .side__group__list--groupname
      = group.name
    .side__group__list--message
      | piyopiyo

app/views/groups/_side_bar.slim
.side__menu
  .side__menu--username
    | ほげ
  .side__menu--tools
    = link_to new_group_path, class: 'new_group' do
      i.fa.fa-pencil-square-o.fa-2 aria-hidden='true'
    = link_to edit_user_registration_path, class: 'tool_config' do
      i.fa.fa-cog.fa-2 aria-hidden='true'
.side__group
  = render partial: 'groups/group', collection: groups

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form', group: @group

app/views/groups/index.slim
.contents
  .side
    = render 'side_bar', groups: @groups
  .main

app/views/groups/messages/_message.slim
li.massage__list
  .message__info
    .message--user
      = message.user.name
    .message--date
      = format_date(message)
  .message__content
    p = message.text
    p = image_tag message.image

app/views/groups/messages/index.slim
.contents
  .side
    = render 'groups/side_bar', groups: @groups
  .main
    .main__header
      .main__header__info
        .main__header__info--groupname
          = @group.name
        .main__header__info--members
          | Members: #{group_users(@group)}
      .main__header--button
        = link_to 'Edit', edit_group_path(@group)

    ul.main__message
      = render partial: 'message', collection: @messages

    .main__form
      .main__form--input
        = form_for @message, url: group_messages_path do |f|
          = f.text_field :text, placeholder: 'type a message', class: 'input_form'
          = f.file_field :image
          i.fa.fa-picture-o.fa-2 aria-hidden='true' class='image_button'
          = f.submit 'Send', class: 'submit_button'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', group: @group

app/views/layouts/_messages.slim
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: 'alert alert-success')
  - if value == alert
    = content_tag(:div, value, class: 'alert alert-danger')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content='text/html; charset=UTF-8' http-equiv='Content-Type'
    title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/messages'
    = yield

app/views/layouts/application.slim
doctype html
html
  head
    meta content='text/html; charset=UTF-8' http-equiv='Content-Type'
    title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/messages'
    = yield

app/views/users/edit.html.erb
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
        = devise_error_messages!
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :password
            %i (変更したくない場合は、空白のままにしておいてください)
          .field-input
            = f.password_field :password, autocomplete: "off"
        .field
          .field-label
            = f.label :password_confirmation
          .field-input
            = f.password_field :password_confirmation, autocomplete: "off"
        .field
          .field-label
            = f.label :current_password
            %i (変更には現在のパスワードの入力が必要です)
          .field-input
            = f.password_field :current_password, autocomplete: "off"
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn'
      = link_to 'トップページに戻る', root_path, class: 'btn'
    .account-page__inner--right.user-form
      = form_for @user do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :password
            %i (変更したくない場合は、空白のままにしておいてください)
          .field-input
            = f.password_field :password, autocomplete: 'off'
        .field
          .field-label
            = f.label :password_confirmation
          .field-input
            = f.password_field :password_confirmation, autocomplete: 'off'
        .field
          .field-label
            = f.label :current_password
            %i (変更には現在のパスワードの入力が必要です)
          .field-input
            = f.password_field :current_password, autocomplete: 'off'
        .actions
          = f.submit 'Update', class: 'btn'